[package]
name = "rstar-benches"
version = "0.1.1"
authors = [
    "Stefan Altmayer <stoeoef@gmail.com>",
    "The Georust Developers <mods@georust.org>",
]
edition.workspace = true
rust-version.workspace = true

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
rand.workspace = true
rand_hc = "0.5"

rstar = { path = "../rstar" }

[[bench]]
name = "benchmarks"
harness = false
